[package]
name = "isaka_james"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
overflow-checks = false
opt-level = "z"

[build]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-Tlinker.ld"
]


